CREATE TABLE IF NOT EXISTS Grades (
    id INTEGER PRIMARY KEY,
    sais_id INTEGER,
    campus_id TEXT,
    term INTEGER,
    section TEXT,
    unit_taken TEXT,
    course_id INTEGER,
    grade TEXT,
    college TEXT,
    grade_type TEXT,
    status TEXT,
    remarks TEXT,
    course_code TEXT,
    student_name TEXT
);

CREATE TABLE IF NOT EXISTS Students (
    id TEXT PRIMARY KEY,
    sais_id TEXT,
    last_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    email TEXT,
    user_roles TEXT,
    tester BOOLEAN,
    created_at TEXT,
    updated_at TEXT,
    google_id TEXT,
    country_of_citizenship TEXT,
    type_of_residency TEXT,
    avatar TEXT,
    name TEXT,
    user_id TEXT,
    campus_id TEXT
);

CREATE TABLE IF NOT EXISTS Classes (
    id INTEGER PRIMARY KEY,
    course_code TEXT,
    course_id INTEGER,
    term_id INTEGER,
    parent_class_id INTEGER,
    type TEXT,
    date TEXT,
    section TEXT,
    time TEXT,
    start_time TEXT,
    end_time TEXT,
    credit TEXT,
    tm_id INTEGER,
    facility_id TEXT,
    max_class_size INTEGER,
    reserved_count INTEGER,
    prerog_count INTEGER,
    active_class_size INTEGER,
    total_enlistment INTEGER,
    activity TEXT,
    acad_org TEXT,
    acad_group TEXT,
    assoc INTEGER,
    class_nbr INTEGER,
    class_status TEXT,
    consent_type TEXT,
    hide_faculty BOOLEAN,
    is_partial_posting BOOLEAN,
    is_parent_class BOOLEAN,
    faculty_grades_assignments TEXT,
    faculties TEXT,
    class_dates TEXT
);

CREATE TABLE IF NOT EXISTS Courses (
    course_id INTEGER PRIMARY KEY,
    sais_course_id INTEGER,
    title TEXT,
    type TEXT,
    description TEXT,
    course_code TEXT,
    sem_offered TEXT,
    career TEXT,
    units TEXT,
    is_repeatable BOOLEAN,
    is_active BOOLEAN,
    campus TEXT,
    equivalent INTEGER,
    is_multiple_enrollment BOOLEAN,
    subject TEXT,
    course_number TEXT,
    contact_hours TEXT,
    grading TEXT,
    tm_id INTEGER,
    acad_org TEXT,
    acad_group TEXT,
    created_at TEXT,
    updated_at TEXT,
    status TEXT,
    is_academic BOOLEAN,
    course_code_title TEXT,
    teaching_model TEXT,
    requisites TEXT
);
