ifneq (,$(wildcard ./.env))
    include .env
    export
endif

ODIR=build
DATA_DIR=data
SCRIPT_DIR=scripts
SQL_DIR=sql
FILTERS_DIR=filters
TERMS_PREFIX := 121 122 123 124 125 126
YEARS := 2021 2022 2023 2024 2025
TARGETS=database collectgrades collectstudents ingest silver gold

filter=$(FILTERS_DIR)/filter.jq
users_filter=$(FILTERS_DIR)/users_filter.jq
students_filter=$(FILTERS_DIR)/students_filter.jq
students_join_filter=$(FILTERS_DIR)/students_join_filter.jq
classes_filter=$(FILTERS_DIR)/classes_filter.jq
courses_filter=$(FILTERS_DIR)/courses_filter.jq
enlistments_filter=$(FILTERS_DIR)/enlistments_filter.jq

terms := \
    $(foreach p,$(TERMS_PREFIX),\
	$(addprefix $(p),1 2 3))

raw_student_grades := \
    $(foreach y,$(YEARS),\
        $(foreach t,$(TERMS_PREFIX),\
            $(DATA_DIR)/student-grades$(t)-$(y).json))

student_ids=student_ids.txt
student_ids_json=$(ODIR)/student_ids.json

bronze_db_name=bronze.db
bronze_db=$(ODIR)/$(bronze_db_name)
silver_db_name=silver.db
silver_db=$(ODIR)/$(silver_db_name)
gold_db_name=gold.db
gold_db=$(ODIR)/$(gold_db_name)

bronze_schema_sql_name=bronze_schema.sql
bronze_schema_sql=$(SQL_DIR)/$(bronze_schema_sql_name)
silver_schema_sql_name=silver_schema.sql
silver_schema_sql=$(SQL_DIR)/$(silver_schema_sql_name)
gold_schema_sql_name=gold_schema.sql
gold_schema_sql=$(SQL_DIR)/$(gold_schema_sql_name)

# bronze is generated by `INGEST_SCRIPT`
silver_sql_name=silver.sql
silver_sql=$(ODIR)/$(silver_sql_name)
gold_sql_name=gold.sql
gold_sql=$(ODIR)/$(gold_sql_name)

grades_json=$(ODIR)/grades.json
_users_json=$(ODIR)/_users.jsonl
_students_json=$(ODIR)/_students.jsonl
students_json=$(ODIR)/students.json
classes_json=$(ODIR)/classes.json
courses_json=$(ODIR)/courses.json
enlistments_json=$(ODIR)/enlistments.json

ingest_script=$(SCRIPT_DIR)/ingest.py

init_sql=$(ODIR)/init.sql

raw_users=$(DATA_DIR)/users.json
raw_students := \
    $(foreach y,$(YEARS),\
	    $(DATA_DIR)/students$(y).json)

raw_classes := \
    $(foreach t,$(TERMS_PREFIX),\
	    $(DATA_DIR)/classes$(t).json)

raw_courses=$(addprefix $(DATA_DIR)/,courses.json)

raw_enlistments := \
    $(foreach y,$(YEARS), \
	    $(foreach t,$(terms), \
		$(DATA_DIR)/student-enlistments$(t)-$(y).json))

ingest_marker_students=$(ODIR)/.ingested_students
ingest_marker_grades=$(ODIR)/.ingested_grades
ingest_marker_classes=$(ODIR)/.ingested_classes
ingest_marker_courses=$(ODIR)/.ingested_courses
ingest_marker_enlistments=$(ODIR)/.ingested_enlistments
bronze_target=$(ODIR)/.last_bronze
silver_target=$(ODIR)/.last_silver
gold_target=$(ODIR)/.last_gold

.phony: all clean collectgrades collectstudents query ingeststudents ingest ingestgrades ingestclasses ingestcourses silver cleanbuild cleandata ingestenlistments gold

all: $(TARGETS)

cleanbuild:
	-rm -r $(ODIR)

cleandata:
	-rm $(raw_courses)
	-rm $(raw_classes)
	-rm $(raw_enlistments)
	-rm $(raw_students)
	-rm $(raw_student_grades)
	-rm $(raw_users)

clean: cleanbuild cleandata

$(init_sql):
	echo ".timeout 10000" > $@
	echo "ATTACH DATABASE '$(bronze_db)' AS bronze;" >> $@
	echo "ATTACH DATABASE '$(silver_db)' AS silver;" >> $@
	echo "ATTACH DATABASE '$(gold_db)' AS gold;" >> $@

silver: $(silver_target)

gold: $(gold_target)

query: $(init_sql) $(silver_target) $(gold_target)
	-sqlite3 -table -header -init $<

ingest: ingeststudents ingestgrades ingestclasses ingestcourses ingestenlistments

ingeststudents: $(ingest_marker_students)

ingestcourses: $(ingest_marker_courses)

ingestgrades: $(ingest_marker_grades)

ingestclasses: $(ingest_marker_classes)
	
ingestenlistments: $(ingest_marker_enlistments)

# we build tables twice since some tables depend on gold as well.
# Order of execution depends on filename ordering (in gold_sql_files)
$(gold_target): $(init_sql) $(gold_sql) $(silver_target)
	sqlite3 -init $< < $(gold_sql)
	sqlite3 -init $< < $(gold_sql)
	touch $@

gold_sql_files=$(wildcard $(SQL_DIR)/gold__*.sql)
$(gold_sql): $(gold_sql_files)
	$(file >$@,)
	$(foreach f,$(gold_sql_files),$(file >>$@,.read $(f)))

# same as gold_target, build tables twice
$(silver_target): $(init_sql) $(silver_sql) $(bronze_target)
	sqlite3 -init $< < $(silver_sql)
	sqlite3 -init $< < $(silver_sql)
	touch $@

$(bronze_target): $(ingest_marker_students) $(ingest_marker_courses) \
	$(ingest_marker_grades) $(ingest_marker_classes) \
	$(ingest_marker_enlistments) | $(bronze_db)
	touch $@

silver_sql_files=$(wildcard $(SQL_DIR)/silver__*.sql)
$(silver_sql): $(silver_sql_files)
	$(file >$@,)
	$(foreach f,$(silver_sql_files),$(file >>$@,.read $(f)))

$(ingest_marker_courses): $(courses_json) | $(bronze_db)
	python $(ingest_script) --db $(bronze_db) courses $(courses_json)
	touch $@

$(ingest_marker_classes): $(classes_json) | $(bronze_db)
	python $(ingest_script) --db $(bronze_db) classes $(classes_json)
	touch $@

$(ingest_marker_students): $(students_json) | $(bronze_db)
	python $(ingest_script) --db $(bronze_db) students $(students_json)
	touch $@

$(ingest_marker_grades): $(grades_json) | $(bronze_db)
	python $(ingest_script) --db $(bronze_db) grades $(grades_json)
	touch $@

$(ingest_marker_enlistments): $(enlistments_json) | $(bronze_db)
	python $(ingest_script) --db $(bronze_db) enlistments $(enlistments_json)
	touch $@

$(ODIR):
	mkdir -p $(ODIR)

database: $(silver_db) $(bronze_db) $(gold_db)

collectstudents: $(students_json)

collectgrades: $(grades_json)

$(enlistments_json): $(enlistments_filter) $(raw_enlistments)
	jq -f $(enlistments_filter) -s $(raw_enlistments) > $@

$(courses_json): $(courses_filter) $(raw_courses)
	jq -f $(courses_filter) -s $(raw_courses) > $@

$(classes_json): $(classes_filter) $(raw_classes)
	jq -f $(classes_filter) -s $(raw_classes) > $@

$(students_json): $(_users_json) $(_students_json) $(students_join_filter)
	jq -n --slurpfile users $(_users_json) --slurpfile students $(_students_json) -f $(students_join_filter) > $@

$(_users_json): $(raw_users) | $(ODIR)
	jq -f $(users_filter) -s $(raw_users) -c > $@

$(_students_json): $(raw_students) $(student_ids_json) | $(ODIR)
	jq -f $(students_filter) --slurpfile ids $(student_ids_json) -s $(raw_students) -c > $@

$(bronze_db): $(bronze_schema_sql) | $(ODIR)
	sqlite3 -cmd '.timeout 10000' $@ < $<

$(silver_db): $(silver_schema_sql) | $(ODIR)
	sqlite3 -cmd '.timeout 10000' $@ < $<

$(gold_db): $(gold_schema_sql) | $(ODIR)
	sqlite3 -cmd '.timeout 10000' $@ < $<

$(student_ids_json): $(student_ids) | $(ODIR)
	jq -R -s -c 'split("\n") | map(select(length > 0))' $< > $@

$(grades_json): $(raw_student_grades) $(student_ids_json) $(filter) | $(ODIR)
	jq --argjson ids '$(shell cat $(student_ids_json))' -f $(filter) -s $(raw_student_grades) > $@

$(DATA_DIR)/users.json:
	./$(SCRIPT_DIR)/fetch_users.sh -o $@ -n

$(DATA_DIR)/student-grades%.json:
	./$(SCRIPT_DIR)/fetch_grades.sh -t $(word 1,$(subst -, ,$*)) -s $(word 2,$(subst -, ,$*)) -o $@

$(DATA_DIR)/students%.json:
	./$(SCRIPT_DIR)/fetch_students.sh -s $* -o $@ -n

$(DATA_DIR)/classes%.json:
	./$(SCRIPT_DIR)/fetch_classes.sh -t $* -o $@ -n

$(DATA_DIR)/courses.json:
	./$(SCRIPT_DIR)/fetch_courses.sh -o $@ -n

$(DATA_DIR)/student-enlistments%.json:
	./$(SCRIPT_DIR)/fetch_enlistments.sh -t $(word 1,$(subst -, ,$*)) -s $(word 2,$(subst -, ,$*)) -o $@
